### ISSUE TITLE
Unable to push test results using jar

### ISSUE THREAD

**Issue by raka2407** [MicroFocus/octane-collection-tool#14]
Hi, below is the error I get while pushing the xml using test-result-collection-tool jar. Kindly help

Octane Version: 12.55.17.164

![image](https://user-images.githubusercontent.com/29482185/69141647-825a1c00-0ac5-11ea-8d10-2c897bc18fa2.png)

**Comment by radislavB** [comment]
Hi.
Can you send me sample.xml to my mail radislav.berkovich@microfocus.com

**Comment by raka2407** [comment]
Hi @radislavB Sample.xml was used from the example provided in this repo. 
test-result-collection-tool/src/test/resources/com/microfocus/mqm/clt/JUnit-minimalAccepted.xml

**Comment by radislavB** [comment]
I uploaded 1.0.10 version : https://github.com/MicroFocus/octane-collection-tool/releases/tag/octane-collection-tool-1.0.10 (there was a bug related to testcase with error but without error message)

About sample.xml - seems like you removed element "testsuite" or didn't close it.
Please check it.
If you didn't find nothing - send it to me anyway.

**Comment by raka2407** [comment]
Thanks, but no luck. Send the sample.xml to you over email.
