### ISSUE TITLE
The HPSoftware organisation is being deprecated!

### ISSUE THREAD

**Issue by slbruce** [MicroFocus/octane-collection-tool#5]
The HPSoftware organisation is being deprecated and all active repositories should be moved to the [https://github.com/MicroFocus](Micro Focus) organisation.

After the 31st December 2017 this organisation and all its repositories will be locked and the HPSoftware organisation will be deleted.

For any questions please contact me or comment on this issue

**Comment by m-seldin** [comment]
repo moved

**Comment by slbruce** [comment]
Can you write a note in the description that this repo has been deprecated and moved?

**Comment by m-seldin** [comment]
@slbruce - the repository **is not depricated**. it has been transfered to the Microfocus organiztion.
the old link relocates the person to the new org. this is how organization transfer works in github.
