### ISSUE TITLE
Import does not support space in environment list

### ISSUE THREAD

**Issue by panama69** [MicroFocus/octane-collection-tool#8]
Octane out of the box has an environment called "AUT Env".  

line 356 of CliParser.java looks to be the issue based on how the regex is created
        Pattern pattern = Pattern.compile("^\\w+:\\w+$");
I think the following would be better as it would support a space in the name (example "AUT Env")
        Pattern pattern = Pattern.compile("/^[\\w+\\s\\w+]+\\w:[\\w+\\s\\w+]+\\w:$/");

I would have made the changes and performed a pull but I have not figured out the correct way to build/package the jar given all the profile options.

A README.md file explaining things would be most helpful in this case.

**Comment by panama69** [comment]
after reading more on Pattern.compile, why wouldn't we be using:
Pattern pattern = Pattern.compile("^[\w+\s\w+]+\w:[\w+\s\w+]+\w:$");

**Comment by radislavB** [comment]
HI.
Thanks for pointing our attention.
We are going to fix it to the following pattern : ^\w([\s\w._]+)?\w:\w([\s\w._]+)?\w$
Do you need fixed tool?

**Comment by panama69** [comment]
The fixed tool would be handy.  I have compiled locally and it seems to be working for me.

**Comment by panama69** [comment]
Are you sure your RegEx is correct?  If I am using the  following
Corn Dog:Good Food

the match would be:
Full match | 0-18 | `Corn Dog:Good Food`
Group 1. | 1-7 | `orn Do`
Group 2. | 10-17 | `ood Foo`

using: https://regex101.com/

**Comment by radislavB** [comment]
fixed in 1.0.7 release
